config/routes.rb
Rails.application.routes.draw do
  get 'apps/index'

  resources :nerds

  resources :servicos

  resources :blogs

  resources :produtos

  resources :landings

  resources :fornecedors

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'apps#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:titulo, :subtitulo, :texto, :tags)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :titulo, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :subtitulo, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :subtitulo, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :texto, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :texto, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tags, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :tags, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  blogs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Blog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blogs/index.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Blog %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:subtitulo) %></th>
      <th><%= model_class.human_attribute_name(:texto) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.id %></td>
        <td><%= blog.titulo %></td>
        <td><%= blog.subtitulo %></td>
        <td><%= blog.texto %></td>
        <td><%= blog.tags %></td>
        <td><%=l blog.created_at, format: :long %></td>
        <td>
          <%= link_to blog_path(blog), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to blog_path(blog), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_blog_path,
            :class => 'btn btn-primary' %>

app/views/blogs/new.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Blog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blogs/show.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Blog %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:titulo) %></dt>
      <dd><pre class="prettyprint"><%= @blog.titulo %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:subtitulo) %></dt>
      <dd><pre class="prettyprint"><%= @blog.subtitulo %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:texto) %></dt>
      <dd><pre class="prettyprint"><%= @blog.texto %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tags) %></dt>
      <dd><pre class="prettyprint"><%= @blog.tags %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              blogs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_blog_path(@blog), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              blog_path(@blog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>