config/routes.rb
Rails.application.routes.draw do
  get 'apps/index'

  resources :nerds

  resources :servicos

  resources :blogs

  resources :produtos

  resources :landings

  resources :fornecedors

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'apps#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/servico.rb
class Servico < ActiveRecord::Base
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :set_servico, only: [:show, :edit, :update, :destroy]

  # GET /servicos
  # GET /servicos.json
  def index
    @servicos = Servico.all
  end

  # GET /servicos/1
  # GET /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
  end

  # GET /servicos/1/edit
  def edit
  end

  # POST /servicos
  # POST /servicos.json
  def create
    @servico = Servico.new(servico_params)

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: 'Servico was successfully created.' }
        format.json { render :show, status: :created, location: @servico }
      else
        format.html { render :new }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicos/1
  # PATCH/PUT /servicos/1.json
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.html { redirect_to @servico, notice: 'Servico was successfully updated.' }
        format.json { render :show, status: :ok, location: @servico }
      else
        format.html { render :edit }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1
  # DELETE /servicos/1.json
  def destroy
    @servico.destroy
    respond_to do |format|
      format.html { redirect_to servicos_url, notice: 'Servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servico_params
      params.require(:servico).permit(:titulo, :descricao, :preco)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
<%= form_for @servico, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :titulo, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :descricao, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preco, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :preco, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  servicos_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Servico %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicos/index.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => Servico %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:preco) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @servicos.each do |servico| %>
      <tr>
        <td><%= servico.id %></td>
        <td><%= servico.titulo %></td>
        <td><%= servico.descricao %></td>
        <td><%= servico.preco %></td>
        <td><%=l servico.created_at, format: :long %></td>
        <td>
          <%= link_to servico_path(servico), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to servico_path(servico), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_servico_path,
            :class => 'btn btn-primary' %>

app/views/servicos/new.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Servico %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicos/show.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => Servico %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:titulo) %></dt>
      <dd><pre class="prettyprint"><%= @servico.titulo %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descricao) %></dt>
      <dd><pre class="prettyprint"><%= @servico.descricao %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:preco) %></dt>
      <dd><pre class="prettyprint"><%= @servico.preco %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              servicos_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_servico_path(@servico), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              servico_path(@servico),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>